apiVersion: gent.io/v1alpha1
kind: application

metadata:
  name: hello-lambda
  owner: aigent-energy

build:
  sdk:
    name: dotnet
    version: "10"
  scripts:
    - dotnet restore
    - dotnet publish src/HelloLambda -c Release -o publish/hello-lambda

artifacts:
  hello-lambda:
    type: files
    path: publish/hello-lambda
    repository: aigent-energy/hello-lambda

platforms:
  lambda:
    apiVersion: gent.io/lambda/v1alpha1
    artifacts: [hello-lambda]
